[package]
name = "rusty-with-graphs"
version = "0.1.0"
authors = ["esqu1 <brandbest1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matrix = "0.22.0"